# Generated by Django 5.2.4 on 2025-08-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("lab", "Lab Report"),
                    ("scan", "Scan/X-ray"),
                    ("prescription", "Prescription"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visitnote",
            name="prescription",
            field=models.FileField(blank=True, null=True, upload_to="prescriptions/"),
        ),
    ]
