# Generated by Django 5.2.4 on 2025-08-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_document_appointment_alter_document_doc_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitnote",
            name="prescription_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="visitnote",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitnote_set",
                to="app.appointment",
            ),
        ),
    ]
