# Generated by Django 5.2.4 on 2025-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_visitnote_prescription_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RemoveField(
            model_name="visitnote",
            name="prescription_text",
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
